### ISSUE TITLE
遇到了一个问题，可能很简单，错误如下

### ISSUE THREAD

**Issue by fan-nian** [CCIIPLab/EACM#1]
Traceback (most recent call last):
  File "baseline.py", line 526, in <module>
    tf.app.run()
  File "C:\Users\Admin\anaconda3\envs\EACM\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "baseline.py", line 523, in main
    train()
  File "baseline.py", line 185, in train
    model = create_model(sess, False, False)
  File "baseline.py", line 118, in create_model
    dtype=dtype)
  File "F:\code\dialoge\EACM-main\seq2seq_model.py", line 146, in __init__
    hidden_size, embedding_size, category, source_vocab_size)
  File "F:\code\dialoge\EACM-main\seq2seq.py", line 1368, in classify_model_with_buckets
    senti_output, senti_cell_state = rnn.rnn(senti_cell, senti_embedded_inputs[:bucket[0]], dtype=tf.float32, scope="senti_encoder")
  File "C:\Users\Admin\anaconda3\envs\EACM\lib\site-packages\tensorflow\python\ops\rnn.py", line 132, in rnn
    raise TypeError("cell must be an instance of RNNCell")
TypeError: cell must be an instance of RNNCell

**Comment by Banana-lwz** [comment]
你好，请问这个问题您是如何解决的？我也遇到了这个问题
