### ISSUE TITLE
raise TypeError("cell must be an instance of RNNCell") TypeError: cell must be an instance of RNNCell

### ISSUE THREAD

**Issue by loveforccy** [CCIIPLab/EACM#3]
报错信息：
Traceback (most recent call last):
  File "baseline.py", line 531, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "baseline.py", line 528, in main
    train()
  File "baseline.py", line 190, in train
    model = create_model(sess, False, False)
  File "baseline.py", line 123, in create_model
    dtype=dtype)
  File "/eacm/seq2seq_model.py", line 148, in __init__
    hidden_size, embedding_size, category, source_vocab_size)
  File "/eacm/seq2seq.py", line 1368, in classify_model_with_buckets
    senti_output, senti_cell_state = rnn.rnn(senti_cell, senti_embedded_inputs[:bucket[0]], dtype=tf.float32, scope="senti_encoder")
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 132, in rnn
    raise TypeError("cell must be an instance of RNNCell")
TypeError: cell must be an instance of RNNCell

**Comment by Banana-lwz** [comment]
你好，请问这个问题您解决了吗？我也碰到了这个问题

**Comment by loveforccy** [comment]
> 你好，请问这个问题您解决了吗？我也碰到了这个问题

没有
